# these values are generated by azure, so they can't be known before apply
# printing them here means I never have to look them up in the portal

# the address to tag and push images to
output "acr_login_server" {
  value = azurerm_container_registry.acr.login_server
}

# needed for az webapp restart
output "resource_group_name" {
  value = azurerm_resource_group.rg.name
}

output "backend_url" {
  value = "https://${azurerm_linux_web_app.backend.default_hostname}"
}

output "frontend_url" {
  value = "https://${azurerm_linux_web_app.frontend.default_hostname}"
}